$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    dots:true,
    mouseDrag: true,
    touchDrag: true,
    responsiveClass:true,
    responsive:{
        0:{
            items:1,
            nav:true
        },
        600:{
            items:3,
            nav:false
        },
        1000:{
            items:5,
            nav:true,
            loop:false
        }
    }
})
$('.owl-carousel1').owlCarousel({
    loop:true,
    margin:10,
    dots:false,
    mouseDrag: true,
    touchDrag: true,
    responsiveClass:true,
    responsive:{
        0:{
            items:1,
            nav:true
        },
        600:{
            items:1,
            nav:false
        },
        1000:{
            items:4,
            nav:true,
            loop:false
        }
    }
})
$('.owl-carousel2').owlCarousel({
    loop:true,
    margin:10,
    dots:true,
    mouseDrag: true,
    touchDrag: true,
    responsiveClass:true,
    responsive:{
        0:{
            items:1,
            nav:true
        },
        600:{
            items:1,
            nav:false
        },
        1000:{
            items:3,
            nav:true,
            loop:false
        }
    }
})